#!/usr/bin/python
# -*- coding: utf-8 -*-
import requests, argparse, os, json, datetime

### GENERAL
parser = argparse.ArgumentParser(description='UAH<>EUR converter using PrivatBank API')
parser.add_argument('amount', metavar='N', type=int, help='amount of currency to convert')
parser.add_argument('curr', metavar='C', type=str, help='currency to convert from')

args = parser.parse_args()

cache = "/tmp/currency_rates.cache"

if os.path.isfile(cache):
  dt=os.path.getmtime(cache)

if os.path.isfile(cache) and (datetime.datetime.utcfromtimestamp(dt) > datetime.datetime.utcnow() - datetime.timedelta(minutes=10)):
  with open(cache, 'r') as f:
    data = json.load(f)
else:
  resp = requests.get("https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5")
  data = resp.json()
  with open(cache, 'w') as f:
    json.dump(data, f)

if args.curr == "eur" or args.curr == "EUR":
	print ("%.2f" % (args.amount*float(data[2]["buy"])))," UAH"
elif args.curr == "uah" or args.curr == "UAH":
	print ("%.2f" % (args.amount/float(data[2]["buy"])))," EUR"
else:
	print "Allowed currencies: UAH|EUR"
